all: ../lib/mainform_impl.py ../lib/msgeditdialog_impl.py \
    ../lib/optionsdialog_impl.py ../lib/msgimport_impl.py \
    ../lib/aboutdialog_impl.py ../lib/applogdialog_impl.py \
    ../lib/msghistorydialog_impl.py ../lib/msgpreviewdialog_impl.py \
    ../lib/spellcheckdialog_impl.py ../lib/mainform2_impl.py \
    ../lib/archviewdialog_impl.py ../lib/repleditdialog_impl.py

../lib/mainform_impl.py : mainform.ui
	pyuic -o ../lib/mainform_impl.py -p 4 -x mainform.ui

../lib/mainform2_impl.py : mainform2.ui
	pyuic -o ../lib/mainform2_impl.py -p 4 -x mainform2.ui

../lib/msgeditdialog_impl.py : msgeditdialog.ui
	pyuic -o ../lib/msgeditdialog_impl.py -p 4 -x msgeditdialog.ui

../lib/optionsdialog_impl.py : optionsdialog.ui
	pyuic -o ../lib/optionsdialog_impl.py -p 4 -x optionsdialog.ui

../lib/msgimport_impl.py : msgimport.ui
	pyuic -o ../lib/msgimport_impl.py -p 4 -x msgimport.ui

../lib/aboutdialog_impl.py : aboutdialog.ui
	pyuic -o ../lib/aboutdialog_impl.py -p 4 -x aboutdialog.ui

../lib/applogdialog_impl.py : applogdialog.ui
	pyuic -o ../lib/applogdialog_impl.py -p 4 -x applogdialog.ui

../lib/msghistorydialog_impl.py : msghistorydialog.ui
	pyuic -o ../lib/msghistorydialog_impl.py -p 4 -x msghistorydialog.ui

../lib/msgpreviewdialog_impl.py : msgpreviewdialog.ui
	pyuic -o ../lib/msgpreviewdialog_impl.py -p 4 -x msgpreviewdialog.ui

../lib/spellcheckdialog_impl.py : spellcheckdialog.ui
	pyuic -o ../lib/spellcheckdialog_impl.py -p 4 -x spellcheckdialog.ui

../lib/archviewdialog_impl.py : archviewdialog.ui
	pyuic -o ../lib/archviewdialog_impl.py -p 4 -x archviewdialog.ui

../lib/repleditdialog_impl.py : repleditdialog.ui
	pyuic -o ../lib/repleditdialog_impl.py -p 4 -x repleditdialog.ui

